---
- name: redistribute static nat route to eigrp4
  ios_config:
    defaults: yes
    parents: router eigrp {{ routing.eigrp_as }}
    lines:
      - redistribute static
  when:
    - interfaces | selectattr('eigrp4', 'defined') | list
    - nat is defined
