---
# https://docs.ansible.com/ansible/2.5/network/user_guide/network_best_practices_2.5.html
- name: "Gather ansible_net_* facts"
  hosts: cisco
  gather_facts: no
  tasks:
    - name: Gather facts (ios)
      ios_facts:
      when: ansible_network_os == 'ios'
      register: output
    - name: Facts from a specific host
      debug:
        var: output
    - name: Display some facts
      debug:
        msg: "{{ ansible_net_hostname }}: {{ ansible_net_version }}"
