---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: cisco
  connection: network_cli
  gather_facts: no
  
  tasks:
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
      register: config_output
      
    - name: RENAME BACKUP
      commands: "mv {{config_output.backup_path}} ./backup/{{inventory_hostname}}.cfg"

    - name: REMOVE NON CONFIG LINES
      lineinfile:
        path: "./backup/{{inventory_hostname}}.cfg"
        line: "Building configuration..."
        state: absent

    - name: REMOVE NON CONFIG LINES - REGEXP
      lineinfile:
        path: "./backup/{{inventory_hostname}}.cfg"
        regexp: 'Current configuration.*'
        state: absent
