---
- import_tasks: configure_banners.yml
  when:
    - ansible_network_os == 'ios'
  tags:
    - banners
    - common
- import_tasks: configure_system.yml
  when:
    - ansible_network_os == 'ios'
  tags:
    - common
